spring:
  application:
    name: java-code-challenge
  datasource:
    url: jdbc:postgresql://localhost:5432/java-code-challenge
    username: postgres
    password: pass
    driver-class-name: org.postgresql.Driver
